id: I96952C6F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:28:28+00:00'
last_modified: '2022-06-10T05:36:56.278160+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10954
  title: གསུང་འབུམ། ཀུན་དགའ་དཔལ་འབྱོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EE14:
      image_group_id: I0836
      title: ''
      total_pages: 558
      order: 1
      base_file: EE14.txt
    8BF9:
      image_group_id: I0837
      title: ''
      total_pages: 532
      order: 2
      base_file: 8BF9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
